### ISSUE TITLE
Docs do not lineup with 1.0.2?

### ISSUE THREAD

**Issue by tbhockey** [mailerlite/mailerlite-ruby#14]
mailerlite-ruby: 1.0.2
rails: 6.1.5
ruby: 2.7.6

I'm having difficulty following the README docs. For starters, the docs namespace every call with `Mailerlite`, but I don't even have `Mailerlite` defined; for me it is `MailerLite`. 

Next, the first "List all subscribers" call results in the following error:
```
> subscribers = MailerLite::Subscribers.new
> response = subscribers.list(filter: { status: 'active' })
Traceback (most recent call last):
        1: from (irb):21
NoMethodError (undefined method `list' for #<MailerLite::Subscribers:0x00007fe2f9e40ca8>)
```

And getting a single subscriber results in this error:
```
> subscribers.get('test@test.com')
Traceback (most recent call last):
        2: from (irb):22
        1: from (irb):23:in `rescue in irb_binding'
NameError (uninitialized constant MailerLite::VERSION)
```

**Comment by danjcosg** [comment]
Happening for me as well

**Comment by dinomh** [comment]
Thank you for pointing this out, new version is now available and the documentation has been fixed as well.
