### ISSUE TITLE
Unmaintained? 

### ISSUE THREAD

**Issue by rohitpaulk** [mailerlite/mailerlite-ruby#19]
We've issued 3 PRs that haven't been looked at in over a month: 

- https://github.com/mailerlite/mailerlite-ruby/pull/18
- https://github.com/mailerlite/mailerlite-ruby/pull/17
- https://github.com/mailerlite/mailerlite-ruby/pull/16

I wrote in to support and according to them the repository is unmaintained: 

> Currently our team does not actively those repositories and we don't do it upon request. If you can please try to explain the issues you are facing here and we could investigate it.

One of the reasons we chose to use mailerlite is the Ruby bindings. If this unmaintained, I'd expect the repository to be archived, or to have a large warning in the README.

Posting this also as a PSA to other companies considering using Mailerlite. Support seems to have made it clear that there's no ETA they can share on these PRs being looked at.

**Comment by dinomh** [comment]
Sorry for the delay, new version is now out. Thank you for your patience 🙏

**Comment by rohitpaulk** [comment]
@dinomh thank you!
