### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by montekaka** [mailerlite/mailerlite-ruby#22]
There is a typo in the README 

To [List all groups](https://github.com/mailerlite/mailerlite-ruby?tab=readme-ov-file#list-all-groups), it should be `.get`, instead of `.list`.

This `groups.list(limit:10, page:1, filter:{'name': 'My'}, sort:'name')`  doesn't work.  But ` groups.get(limit:10, page:1, filter:{'name': 'My'}, sort:'name')` works

**Comment by dinomh** [comment]
This will fixed resolved in the next version, thank you 👍
