### ISSUE TITLE
/group subscribers is using cursor pagination

### ISSUE THREAD

**Issue by montekaka** [mailerlite/mailerlite-ruby#24]
This [method](https://github.com/mailerlite/mailerlite-ruby/blob/main/lib/mailerlite/groups/groups.rb#L57) is expecting a page parameter, but the API is using cursor pagination.

API doc: https://developers.mailerlite.com/docs/groups.html#get-subscribers-belonging-to-a-group

Maybe consider to update method to expect with a cursor instead?

**Comment by dinomh** [comment]
Updated ✅
