### ISSUE TITLE
README Update incorrect

### ISSUE THREAD

**Issue by bananatron** [mailerlite/mailerlite-ruby#26]
The readme shows:
`subscribers.update(email:'some@email.com', fields: {'name': 'John', 'last_name': 'Doe'}, ip_address:'1.2.3.4', optin_ip:'1.2.3.4')`

BUT it seems the correct usage is without that first param:
`subscribers.update('some@email.com', fields: {'name': 'John', 'last_name': 'Doe'}, ip_address:'1.2.3.4', optin_ip:'1.2.3.4')`

**Comment by dinomh** [comment]
Updated ✅
